[tox]
envlist=py314

[testenv]
extras=
    test
    ui
setenv=
    QT_QPA_PLATFORM=offscreen
commands=
    pytest --no-xvfb tests --cov pyqttoolkit --ignore tests/services/test_task_runner.py
    python scripts/check_license_headers.py
